apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  namespace: dg0413-lifesub-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: member
        image: acrdigitalgarage03.azurecr.io/dg0413/member:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: common-configmap
        - configMapRef:
            name: member-configmap
        - secretRef:
            name: common-secret
        - secretRef:
            name: database-secret
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
